src/App.js, src/components/Header/index.js
=> response working

src/App.js
- Completed user login logic, user stores user info and bearer key in state upon logging in
=> latest update, finished current_user logic

src/App.js, src/components/LessonNav/index.js
- Finished LessonNav logic, utilizing last_l column of users
=> lessonNav functional, utilizing last_l column in users

src/App.js, src/components/Footer/Progress/Bar/index.js, src/components/Footer/Progress/index.js, src/components/LessonNav/index.js, src/components/MainContent/Question/MultChoice/index.js, src/pages/Home/Admin/NewUser/index.js, src/pages/Home/Content/index.js
- added notes for harrison in Footer component
=> notes for harrison

README.md, src/App.js, src/components/Footer/Progress/index.js, src/components/Footer/index.js, src/pages/Home/Content/index.js, src/pages/Home/index.js
- Moved footer bar logic to App.js, removed the additional componentDidMount. Percentage sits inside the App.js now
=> Move bar logic to app.js

src/components/Footer/index.js, src/pages/Home/Content/index.js
- Added content logic, incomplete logic. Need user to response with json for me to complete logic
=> added content logic, incomplete

README.md, src/App.js, src/components/Footer/index.js, src/components/MainContent/Question/MultChoice/index.js, src/components/MainContent/Question/index.js, src/components/MainContent/index.js, src/pages/Home/Content/index.js, src/pages/Home/SignIn/index.js
- added refresh on sign in, directs you to main page
=> Add sign in, refresh on signin

src/App.js, src/components/Header/index.js
Added logout function to App.js
Added logout button to Header component.
Fixed checkuser functionality on header to check if the user is logged in or not.
=> Add logout functionality and button to header

package-lock.json, src/App.js, src/components/Footer/Progress/Bar/index.js, src/components/Footer/index.js, src/components/Header/index.js, src/components/MainContent/Question/IdeChoice/index.js, src/components/MainContent/Question/MultChoice/index.js, src/pages/Home/Admin/NewUser/index.js, src/pages/Home/Admin/index.js, src/pages/Home/Content/index.js
- Add admin panel logic
- Add routes for Admin
- Create logic for admin header
=> add admin panel

src/App.js, src/components/Footer/index.js, src/components/Header/index.js, src/components/MainContent/index.js, src/pages/Home/Admin/NewUser/index.js
- Render lesson through continue
- Show lesson img if not null
=> Render lesson with continue button, show lesson img

src/App.js, src/components/Footer/index.js, src/components/MainContent/index.js, src/components/MainContent/style.css, src/pages/Home/Admin/NewUser/index.js, src/pages/Home/Admin/index.js, src/pages/Home/Content/index.js
- Footer logic now working
- Need to update user info in real time to continue
=> Resolve footer logic

package.json, src/App.js, src/util/api.js
=> Heroku logic

src/App.js, src/components/Footer/Progress/index.js, src/components/Footer/index.js, src/components/Footer/style.css, src/components/Header/index.js, src/pages/Home/Content/index.js
- current_user updating when user answers question correct
- bar now rendering as user answers questions
=> Update user data on question completion

package.json, src/App.js, src/components/Footer/index.js, src/components/Footer/style.css, src/pages/Home/SignIn/index.js, src/util/api.js
- Continue button changes color variant to green if the user gets the answer correct
=> Add color variant to continue button

package.json, src/App.js, src/components/Footer/index.js, src/pages/Home/SignIn/index.js
- Continue button variant is gray for lessons, blue for questions if they are unanswered, and green if they get the right answer.
- Button disabled if question and user hasn't select an option
=> Finish disabled button logic

src/components/MainContent/Question/IdeChoice/index.js, src/components/MainContent/Question/index.js, src/components/MainContent/index.js, src/pages/Home/Content/index.js, src/pages/Home/SignIn/index.js
Created method for IdeChoice and passed props down to it.
=> Pass question down props to use in IdeChoice/index.js

package.json, src/App.js, src/components/Footer/index.js, src/components/MainContent/Question/IdeChoice/index.js, src/components/MainContent/Question/index.js, src/components/MainContent/index.js, src/pages/Home/Content/index.js, src/pages/Home/SignIn/index.js
- Completed IDE check answer, user is able to check answer on IDE
- Created two separate states in content, one for codeMirror and another to check user answer
=> Complete IDE check answer

src/components/MainContent/style.css, src/pages/Home/Content/index.js, src/pages/Home/SignIn/index.js, src/pages/Home/SignIn/style.css
- Img content fixed margins
- login page input fields width fixed
=> Fix content img

src/App.js, src/components/Footer/index.js, src/components/MainContent/Question/IdeChoice/index.js, src/components/MainContent/Question/IdeChoice/style.css, src/components/MainContent/Question/index.js, src/components/MainContent/index.js, src/pages/Home/Admin/NewUser/index.js, src/pages/Home/Admin/NewUser/style.css, src/pages/Home/Content/index.js
- Reset admin create user field
- Copy clipboard added to admin panel when creating a user
- Refactored some components
=> Reset admin fields

src/pages/Home/SignIn/index.js
Fixed the merge conflict on this branch and added in logic to make the login button be able to be used with on-click or pressing enter.
=> Add signin logic to login button

src/App.js, src/pages/Home/Admin/NewUser/index.js, src/pages/Home/Admin/UserProgress/index.js, src/pages/Home/Admin/index.js, src/pages/Home/Content/index.js
- Users Progress now showing on admin panel
=> Add users Progress

src/pages/Home/Content/index.js
Added in thumbs up emoji to correct and an 🚫to incorrect, try again.
=> Add in additional UX for correct or incorrect

src/App.js, src/components/Footer/Progress/index.js, src/components/Footer/index.js, src/components/LessonNav/index.js, src/components/MainContent/index.js, src/pages/Home/Content/index.js
- CardBody implemented on all content
=> Add card to content

src/App.js, src/pages/Home/Admin/NewUser/index.js, src/pages/Home/Admin/UserProgress/index.js, src/pages/Home/Admin/index.js
-Admin now able to toggle between viewing all the users and creating a user via admin panel
=> Toggle Admin Dashboard

src/components/MainContent/index.js, src/pages/Home/Admin/NewUser/index.js, src/pages/Home/Admin/UserProgress/index.js
- fixed function load error on maincontent
=> Fix content function error

src/App.js, src/pages/Home/SignIn/ForgotPass/index.js, src/pages/Home/SignIn/index.js
Added forgot password component/page.
Created forgot password form logic.
Added link to forgot password on SignIn component.
=> Add forgot password component

src/App.js, src/components/Footer/index.js, src/components/Footer/style.css, src/components/LessonNav/index.js, src/pages/Home/Admin/UserProgress/index.js, src/pages/Home/Admin/index.js, src/pages/Home/Content/index.js
- As a user I can see an icon that has a tooltip on hover, upon clicking it opens a modal.
- modal has placeholder text, information will be passed once routes for hints is setup as well as seeds
=> Add hint/suggestions

src/components/Footer/LearnFooter/index.js, src/components/Footer/LearnFooter/style.css
Added in styling to the learn footer to match the website flow. The app seems to be broken so I will leave just this PR until resolved.
=> Add styling to learn footer to match learnacademy.org

src/App.js
-Defaulted back to original redirect template
=> Fix temp redirect issue
